### ISSUE TITLE
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

### ISSUE THREAD

**Issue by ghost** [Marxlp/pyFlightAnalysis#10]
i'm getting an error when i try to run the analysis file
![untitled](https://user-images.githubusercontent.com/25317204/44305495-3ab28500-a396-11e8-9456-2f6556e2584b.png)

**Comment by Marxlp** [comment]
It's a issue due to system supporting. You can find solutions by google.

**Comment by ghost** [comment]
thanks i got it done

**Comment by youtah** [comment]
I know this is already closed, but wanted to leave a comment for people looking in the future. 

Simply running `sudo apt-get install freeglut3-dev` resolved the problem for me on Ubuntu 20.04. FYI
