### ISSUE TITLE
shows me nothing , gives me an error 

### ISSUE THREAD

**Issue by ghost** [Marxlp/pyFlightAnalysis#12]
[
![pyf](https://user-images.githubusercontent.com/25317204/44532137-003b4600-a710-11e8-84b9-6699c54c2be5.png)
](url)

gives me q[o] then saying out of index range when i upload , it doesnt show anything, i'm running on iwndows  10

**Comment by Marxlp** [comment]
Could you send your log file to me and I will check it. My email lipi26@163.com.

**Comment by chataign** [comment]
Hi, I have the same problem on Ubuntu 16.04. I can get log information using `ulog_info`, `ulog_params`, etc. but when I load my logs into `pyFlightAnalysis`, nothing happens. I just emailed you a couple of example logs. Thanks and let me know if you need anything else to look into this issue. 

Kind regards,

**Comment by chataign** [comment]
I tried this simple test with one of my log files:

```
from pyulog.core import ULog
log_file_name = str(sys.argv[1])
log_data = ULog(log_file_name).data_list
```

```
Traceback (most recent call last):
  File "ulog_test.py", line 6, in <module>
    log_data = ULog(log_file_name).data_list
  File "/usr/local/lib/python2.7/dist-packages/pyulog/core.py", line 108, in __init__
    self._load_file(log_file, message_name_filter_list)
  File "/usr/local/lib/python2.7/dist-packages/pyulog/core.py", line 428, in _load_file
    self._read_file_header()
  File "/usr/local/lib/python2.7/dist-packages/pyulog/core.py", line 450, in _read_file_header
    raise Exception("Invalid file format (Failed to parse header)")
Exception: Invalid file format (Failed to parse header)
```

I am using pyulog v0.6.0 and my logs are generated by the current master of px4/Firmware nuttx_px4fmu-v2_default.cmake

**Comment by chataign** [comment]
Since this is a pyulog issue I created an issue in that repo also.

**Comment by Marxlp** [comment]
I checked the files you sent to me. It figure out that file ```log_370_2018-10-25-17-25-56.ulg``` was a bad file with all zero bytes, while the file ```log_368_2018-10-25-16-52-48.ulg``` is okay and can be parsed by ```pyulog```. After using the second file, I found the problem and fixed it. So you can update to the newest version. :smile:
