### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by egorfolley** [Marxlp/pyFlightAnalysis#14]
I successfully installed pyFlighAnalysis but I'm stuck when trying to start it. I'm using Ubuntu 18.04 and I have next error:
`egor@egor:~/Documents/pyFlightAnalysis/src$ python analysis.py `
`python: symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers`
What seems to be the problem and how can I resolve it ?

**Comment by Marxlp** [comment]
Could you give me more information, such as python running environment and packages list?

**Comment by egorfolley** [comment]
Duplicate of #14
Marxlp, sorry for bothering, I solved my problem via installing it using conda =)
But now I have next issue:

> `Traceback (most recent call last):

>   File "/home/follia/anaconda3/bin/analysis", line 11, in <module>
>    load_entry_point('pyFlightAnalysis==1.0.7b0', 'console_scripts', 'analysis')()
>   File "/home/follia/anaconda3/lib/python3.6/site-packages/pyflightanalysis/analysis.py", line 707, in main
>    mainwin = MainWindow()
>   File "/home/follia/anaconda3/lib/python3.6/site-packages/pyflightanalysis/analysis.py", line 146, in __init__
    self.quadrotor_win = QuadrotorWin(self)
  File "/home/follia/anaconda3/lib/python3.6/site-packages/pyflightanalysis/widgets.py", line 65, in __init__
    self.quadrotor_widget = QuadrotorWidget(self.quadrotor_win_main_widget)
  File "/home/follia/anaconda3/lib/python3.6/site-packages/pyflightanalysis/widgets.py", line 196, in __init__
    glutInit()
  File "/home/follia/anaconda3/lib/python3.6/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/follia/anaconda3/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,

> OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling`

But, I quess this problem caused by my sysytem

**Comment by Marxlp** [comment]
It seems that `freeglut` is missing on your system. Try below commands, if you are using Ubuntu:

> sudo apt-get install freeglut3 
> sudo apt-get install freeglut3-dev

**Comment by egorfolley** [comment]
@Marxlp  Thank's a lot! that worked out
