### ISSUE TITLE
How Can I solve it?

### ISSUE THREAD

**Issue by Fllying** [Marxlp/pyFlightAnalysis#18]
$ analysis
Gtk-Message: 15:56:58.511: Failed to load module "canberra-gtk-module"
None
<pyflightanalysis.analysis.TableView object at 0x7f4d516d2190>
Traceback (most recent call last):
  File "/home/whu/.local/lib/python2.7/site-packages/pyflightanalysis/analysis.py", line 305, in callback_open_log_file
    with open(get_source_name('config.txt'), 'r+') as conf:
IOError: [Errno 2] No such file or directory: '/home/whu/.local/lib/python2.7/site-packages/pyflightanalysis/config.txt'
Traceback (most recent call last):
  File "/home/whu/.local/lib/python2.7/site-packages/pyflightanalysis/analysis.py", line 305, in callback_open_log_file
    with open(get_source_name('config.txt'), 'r+') as conf:
IOError: [Errno 2] No such file or directory: '/home/whu/.local/lib/python2.7/site-packages/pyflightanalysis/config.txt'
None
Appriciate your help, thanks

**Comment by Marxlp** [comment]
It's an unsolved bug in the repo. The application tried to load `config.txt`, but forgot to create it if it didn't exist.
To give a quick shot at it, run command blow:

>> touch /home/whu/.local/lib/python2.7/site-packages/pyflightanalysis/config.txt
