### ISSUE TITLE
ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt'

### ISSUE THREAD

**Issue by paulr4** [Marxlp/pyFlightAnalysis#21]
I'm trying to use pyFlightAnalysis on Windows 10, following the 'run from source' instructions in the [readme](https://github.com/Marxlp/pyFlightAnalysis).

When I try to run analysis.py, I'm getting the error:

`ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt'`

Am I doing something wrong, or is something broken?

**Comment by m1baldwin** [comment]
Seeing the same thing on Ubuntu 18.04 as well, after following the installation instructions to install from pip

**Comment by Marxlp** [comment]
Could you give your versions of `pyqtgraph` and **qt bindings** for python here?

**Comment by paulr4** [comment]
For me (Windows), pyqtgraph is version 0.12.2. How do I find the qt bindings version?
[edit - corrected pyqtgraph version, numpy is 1.21.1]

**Comment by Marxlp** [comment]
run `pip list` and find `PyQt` or `PySide` from the output.

**Comment by paulr4** [comment]
I see the following:

```
PyOpenGL         3.1.5
PyQt5            5.15.4
PyQt5-Qt5        5.15.2
PyQt5-sip        12.9.0
pyqtgraph        0.12.2
```

**Comment by Marxlp** [comment]
Try executing `from pyqtgraph.Qt import QtOpenGL` in your python interpreter, and see whether it will be fine.

**Comment by paulr4** [comment]
I get the following:
```
>>> from pyqtgraph.Qt import QtOpenGL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt' (C:\Users\paulr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-pa
ckages\pyqtgraph\Qt\__init__.py)
```

**Comment by Marxlp** [comment]
This may due to the code structure change in `pyqtgraph` library.Currently to solve the issue, you can try version **0.10.0** for `pyqtgraph`. I will update the code on the repo when I am free.

**Comment by paulr4** [comment]
Thanks, I solved my pyqtgraph problem with `pip install pyqtgraph==0.10.0`.
Now I get:
```AttributeError: module 'time' has no attribute 'clock'```
Which seems to have been [removed after Python 3.7](https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8).

**Comment by AlNaCl** [comment]
I have met the same problem in Python3.10.0.

**Comment by Marxlp** [comment]
try using `pyqtgraph==0.11.0`

**Comment by AlNaCl** [comment]
I have solved the problem.The version of python results in this problem.

**Comment by yeshangjun** [comment]
> I have solved the problem.The version of python results in this problem.

which version of python do you use?
I have tried 3.6, 3.7, 3.10
still got the error

**Comment by LukesFatherDarth** [comment]
@AlNaCl > I have solved the problem.The version of python results in this problem.

Which python version have you used to solve the problem?
