### ISSUE TITLE
Undefined function glutInit

### ISSUE THREAD

**Issue by paulr4** [Marxlp/pyFlightAnalysis#22]
I'm trying to use pyFlightAnalysis on Windows 10, following the 'run from source' instructions in the [readme](https://github.com/Marxlp/pyFlightAnalysis).

Following the advice [here](https://github.com/Marxlp/pyFlightAnalysis/issues/21), I believe I'm running the right versions of everything; Python 3.7 (using virtualenv), and pyqtgraph 0.10.0.

When I try to run analysis.py, it fails with the following error:

`OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling`

What can I do to fix this?

**Comment by Marxlp** [comment]
Could you give the versions of your python 3rd packages here?

**Comment by paulr4** [comment]
Python is version 3.7.9, and 'pip list' returns:
```
Package          Version
---------------- -------
cycler           0.10.0
kiwisolver       1.3.2
matplotlib       3.4.3
numpy            1.21.2
Pillow           8.4.0
pip              21.2.4
pyFlightAnalysis 1.1.0b0
PyOpenGL         3.1.5
pyparsing        2.4.7
PyQt5            5.15.4
PyQt5-Qt5        5.15.2
PyQt5-sip        12.9.0
pyqtgraph        0.10.0
python-dateutil  2.8.2
pyulog           0.9.0
setuptools       58.1.0
six              1.16.0
wheel            0.37.0
```

**Comment by Marxlp** [comment]
The answer on https://stackoverflow.com/questions/26700719/pyopengl-glutinit-nullfunctionerror may be helpful.
