### ISSUE TITLE
Cannot run from sourse

### ISSUE THREAD

**Issue by ZhangChi-fd** [Marxlp/pyFlightAnalysis#23]
I tried to install and run in anaconda environment

after I type "python analysis,py"

comes the error:

ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt' (/home/zhangyuyang/anaconda3/envs/learn/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py)

**Comment by Marxlp** [comment]
This may be due to the update of pyqtgraph. Try to install `pyqtgraph==0.11.0`.
