### ISSUE TITLE
ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt'

### ISSUE THREAD

**Issue by nihavend** [Marxlp/pyFlightAnalysis#24]
Traceback (most recent call last):
  File "analysis.py", line 23, in <module>
    from widgets import (QuadrotorWin, InfoWin, ParamsWin, 
  File "/home/parallels/dev/github/pyFlightAnalysis/src/widgets.py", line 8, in <module>
    from pyqtgraph.Qt import QtCore,QtGui,QtOpenGL
ImportError: cannot import name 'QtOpenGL' from 'pyqtgraph.Qt' (/home/parallels/.local/lib/python3.8/site-packages/pyqtgraph/Qt/__init__.py)

Ubuntu 20.04 (ARM)
Python 3.8.10

**Comment by Marxlp** [comment]
Same issue as #23. Try to install `pyqtgraph==0.11.0`.
