### ISSUE TITLE
Encountered problem loading ulg file

### ISSUE THREAD

**Issue by shinfang** [Marxlp/pyFlightAnalysis#7]
Hi there,

I encountered problem while trying to load the ulg file via the user interface. It appears to complain no such file/directory.

**Comment by Marxlp** [comment]
Could you show your the error message here.

**Comment by shinfang** [comment]
Yes. The screenshot of the warning and error message is as per below.

<img width="1155" alt="screen shot 2018-05-24 at 10 21 17 am" src="https://user-images.githubusercontent.com/34994104/40458642-45bc6e96-5f3c-11e8-9d79-7aaa984b4fae.png">

**Comment by Marxlp** [comment]
It seem that you ran `pyFlightAnalysis` on Windows. It's a bug due to the different return result of `QFileDialog` on different OS. 
It's a bug and has been fixed. Therefore you can install newest version as discribed in `README`.
