### ISSUE TITLE
ubuntu mate "No matching distribution found for PyQt5"

### ISSUE THREAD

**Issue by alexxtasi** [Marxlp/pyFlightAnalysis#8]
Hi there,
trying to install on ubuntu mate 16.04 I do the steps:
- sudo apt install python3-pip
- pip3 install --upgrade pip
- pip3 install PyQt5

in this last step there is an error:
```No matching distribution found for PyQt5```

also tried to install PyQt5 in the system with ```sudo apt install python3-pyqt5```, but then the pyFlightAnalysis installation failed with:
```
pip3 install pyFlightAnalysis
Could not install packages due to an EnvironmentError: [Errno 13]
```
what can I do for this ?

**Comment by alexxtasi** [comment]
Oups!
now I see ... PyQt5 (the pip3 method) runs only for linux 32-bit systems!!!
Probably I need to compile it
... closing
(any suggestions are thankful...)

**Comment by Marxlp** [comment]
What's the version of your Python3? Noting that Python3  with versions before 3.5 can't install PyQt5 directly by using ```pip``` if not updating sip, which is used to compile the Qt5 for Python.

**Comment by alexxtasi** [comment]
hi @Marxlp 
it's 3.6.5... on a fresh ubuntu-mate 32bit installation

**Comment by Marxlp** [comment]
So your Ubuntu is 32bit?

**Comment by alexxtasi** [comment]
yes! 
and I read that PyQt5 in only for 64 bit linux installations!!
going for windows platform (the specific cpu is 32bit) ? :(

**Comment by Marxlp** [comment]
Maybe, if you don't want try compile it yourself. Or you can using PyQt4 under python2.x, in which you can install pyqt by ```anaconda``` environment manager.

**Comment by alexxtasi** [comment]
new problem... command ```pip install pyqt4``` failed with "No matching distribution found for pyqt4"
I am using python-2.7 and pip is in version 9.0.1 and updated in latest version comes with "ImportError: cannot import name main" !!

Should I go with anaconda ?

**Comment by Marxlp** [comment]
Yes, have a try.

**Comment by alexxtasi** [comment]
well I tried using Miniconda and Anaconda for python-2 (Miniconda2 and Anaconda2 from [here](https://conda.io/docs/user-guide/install/linux.html)), but I could not install both of them !
Error occurred:
```
[/home/ubuntu/miniconda2] >>>
PREFIX=/home/ubuntu/miniconda2
installing: python-2.7.14-h1571d57_31 ...
Downloads/Miniconda2-latest-Linux-x86.sh: line 355:  2794 Illegal instruction     (core dumped) 
 $PREFIX/pkgs/python-2.7.14-h1571d57_31/bin/python" -E -s "$PREFIX"/pkgs/.install.py $INST_OPT --root-prefix="$PREFIX" --link-dist="$1"
```
Maybe it's anaconda's problem or a problem with python version (ubuntu mate 32bit comes with python 2.7.15rc1).
I know this is not a pyFlightAnalysis's problem but have you or anyone else faced it ?

regards

**Comment by alexxtasi** [comment]
well... forget my last comment...
(testing in a vm with the same OS, miniconda installs with no errors)

so my new state (on a linux 32bit system using python2) is:

- python 2 (```Python 2.7.14 :: Anaconda, Inc.```)
- conda installed (```conda 4.5.4```)
- installed pyqt with ```conda install pyqt```
- installed pyFlightAnalysis with ```pip install pyflightanalysis```
but when trying to run ```analysis``` this comes:
```
Traceback (most recent call last):
  File "/home/tony/miniconda2/bin/analysis", line 11, in <module>
    sys.exit(main())
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pyflightanalysis/analysis.py", line 697, in main
    mainwin = MainWindow()
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pyflightanalysis/analysis.py", line 146, in __init__
    self.quadrotor_win = QuadrotorWin(self)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pyflightanalysis/widgets.py", line 67, in __init__
    self.quadrotor_widget = QuadrotorWidget(self.quadrotor_win_main_widget)
  File "/home/tony/miniconda2/lib/python2.7/site-packages/pyflightanalysis/widgets.py", line 198, in __init__
    glutInit()
  File "/home/tony/miniconda2/lib/python2.7/site-packages/OpenGL/GLUT/special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "/home/tony/miniconda2/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling
```
any suggestions ?
regards

**Comment by Marxlp** [comment]
Have you solved your problem? If you haven't, you may need install freeglut. BTW, googling the last line of the error info will give you more proper solutions.

**Comment by alexxtasi** [comment]
my resolution is that my target machine (it's cpu) is too old for pqyqt, even miniconda (see this [issue](https://github.com/conda/conda/issues/7366)), so I set requirements and found another new machine (linux 64bit), where the installation is flawless .

By the way, the installation process (steps) work on windows machines, but when running analysis, some python errors comes up (other modules should be installed also), but I cannot provide you any info about this, since I did many attempts and did not take notes ;-) 

thanks anyway
