### ISSUE TITLE
AttributeError causing pyFlightAnalysis to crash

### ISSUE THREAD

**Issue by rallen10** [Marxlp/pyFlightAnalysis#9]
When I import a flight log I get a message saying: `'odict_keys' object has no attribute 'index'`, but the program continues to run. When I try to open a particular data stream, for example vehicle_local_position, it causes a crash saying

```
Traceback (most recent call last):
  File "/home/ross/miniconda2/envs/flight_log_analysis/lib/python3.6/site-packages/pyflightanalysis/analysis.py", line 457, in callback_tree_double_clicked
    data_index = self.data_dict.keys().index(item_label.split('->')[0])
AttributeError: 'odict_keys' object has no attribute 'index'
Aborted (core dumped)
```

**Comment by Marxlp** [comment]
This is due to the different versions of python in the action of dict's keys method. And I have fixed it. So you can download the newest version.
